__version__: 1.3.0
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params:
    angle_in_degrees: true
    check_each_transform: true
    format: xy
    label_fields: null
    remove_invisible: true
  p: 1.0
  transforms:
  - __class_fullname__: ToFloat
    always_apply: true
    max_value: 255
    p: 1.0
  - __class_fullname__: Resize
    always_apply: false
    height: 512
    interpolation: 1
    p: 1
    width: 256
  - __class_fullname__: Normalize
    always_apply: true
    max_pixel_value: 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    p: 1.0
    std:
    - 0.229
    - 0.224
    - 0.225
  - __class_fullname__: ToTensorV2
    always_apply: true
    p: 1.0
    transpose_mask: false
